id: starter_content_creation
description: Starter workflow (editable) for docs/marketing/content with iterative production stories and editorial review.
stages:
  - ref: research
    agent: research
    optional: true
    condition: unknowns_exist

  - ref: plan
    agent: plan

  - ref: plan_review
    agent: plan_review
    loopTarget: plan
    maxIterations: 2

  - ref: content_stories
    agent: ui
    type: loop
    loop:
      over: stories
      completion: all_done
      verifyEach: true
      verifyStageRef: content_review
      maxStories: 20

  - ref: content_review
    agent: ui_review
    loopTarget: content_stories
    maxIterations: 2

  - ref: security
    agent: security
    optional: true
    condition: security_relevant
    canVeto: true
    loopTarget: content_stories
    maxIterations: 1
