id: starter_bug_fix
description: Starter workflow (editable) for bug fixes with plan gate, iterative fix stories, and verification.
stages:
  - ref: research
    agent: research
    optional: true
    condition: unknowns_exist

  - ref: plan
    agent: plan

  - ref: plan_review
    agent: plan_review
    loopTarget: plan
    maxIterations: 1

  - ref: build_stories
    agent: build
    type: loop
    loop:
      over: stories
      completion: all_done
      verifyEach: true
      verifyStageRef: build_review
      maxStories: 15

  - ref: build_review
    agent: build_review
    loopTarget: build_stories
    maxIterations: 2

  - ref: security
    agent: security
    optional: true
    condition: security_relevant
    canVeto: true
    loopTarget: build_stories
    maxIterations: 1
